/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Holo(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./barista/holohoodie2-transformed.glb')
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    // Reset and fade in animation after an index has been changed
    actions[names[0]].reset().fadeIn(0.5).play()
    // In the clean-up phase, fade it out
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Body" geometry={nodes.Body.geometry} material={materials['Material.002']} skeleton={nodes.Body.skeleton} />
          <skinnedMesh name="Full_Body13Clothes_Hair1" geometry={nodes.Full_Body13Clothes_Hair1.geometry} material={materials['Material.001']} skeleton={nodes.Full_Body13Clothes_Hair1.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./barista/holohoodie2-transformed.glb')
